config/routes.rb
Ticketee::Application.routes.draw do
  default_url_options :host => "localhost:3000"

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    post '/signin' => 'devise/sessions#create'
    delete '/signout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end
  resources :users, :only => :show
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end

    end

  end
  resources :files

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end

  end

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end

  root 'projects#index'
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, polymorphic: true

end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_action :set_user

  def index
    @ability = Ability.new(@user)
    @projects = Project.all
  end

  def set
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      project = Project.find(id)
      permissions.each do |permission, checked|
        Permission.create!(user: @user,
                           thing: project,
                           action: permission)
      end
    end
    flash[:notice] = "Permissions updated."
    redirect_to admin_user_permissions_path(@user)
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end

end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
  module Admin::PermissionsHelper
    def permissions
      {
          "view" => "View",
          "create tickets" => "Create Tickets",
          "edit tickets" => "Edit Tickets",
          "delete tickets" => "Delete Tickets",
          "change states" => "Change States",
          "tag" => "Tag"
      }
    end
  end

end

app/views/admin/permissions/index.html.erb
<h2>Permissions for <%= @user.email %></h2>
<%= form_tag admin_user_set_permissions_path, :method => :put do %>
    <table id='permissions' cellspacing='0'>
      <thead>
      <th>Project</th>
      <% permissions.each do |name, text| %>
          <th><%= text %></th>
      <% end %>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
          <tr class='<%= cycle("odd", "even") %>'
              id='project_<%= project.id %>'>
            <td><%= project.name %></td>
            <% permissions.each do |name, text| %>
                <td>
                  <%= check_box_tag "permissions[#{project.id}][#{name}]",
                                    @ability.can?(name.to_sym, project),
                                    @ability.can?(name.to_sym, project) %>
                </td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= submit_tag "Update" %>
<% end %>