config/routes.rb
Ticketee::Application.routes.draw do
  default_url_options :host => "localhost:3000"

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    post '/signin' => 'devise/sessions#create'
    delete '/signout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end
  resources :users, :only => :show
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end

    end

  end
  resources :files

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end

  end

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end

  root 'projects#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable, :validatable
  has_many :permissions
  before_save :ensure_authentication_token

  def self.reset_request_count!
    update_all("request_count = 0", "request_count > 0")
  end

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  private



  # def ensure_authenticaion_token
 #   reset_authentication_token if authentication_token.blank?
 # end

 # def reset_authentication_token
 #   self.authentication_token = self.class.authentication_token
 # end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    params = user_params.dup
    params[:password_confirmation] = params[:password]
    @user = User.new(params)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render :action => "new"
    end
  end

  def show

  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been updated."
      render action: "edit"
    end
  end

  def destroy
    if @user==current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end

    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :admin)
  end

  def get_user
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:show, :update]
=begin
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      flash[:notice] = "You have signed up successfully."
      redirect_to projects_path
    else
      render "new"
    end
  end

  def edit

  end
=end
  def show
  end

  #def update
  #  if user_params[:password].blank? and user_params[:password_confirmation].blank?
  #    user_params.delete(:password)
  #    user_params.delete(:password_confirmation)
  #  end
  #  if @user.update(user_params)
  #    flash[:notice] = "Profile has been updated."
  #    redirect_to @user
  #  else
  #    flash[:alert] = "Profile has not been updated."
  #    render :edit
  #  end
#
  #end


  private
  #def user_params
  #  params.require(:user).permit(:name,
  #                               :email,
  #                               :password,
  #                               :password_confirmation)
  #end
#
 def set_user
   @user = User.find(params[:id])
  end
#
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.check_box :admin %>
      <%= f.label :admin, "Is an admin?" %>
    </p>

    <%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing a User</h2>
<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %>
<ul id='users'>
  <% @users.each do |user| %>
      <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), method: :delete,
            data: { confirm: "Are you sure you want to delete this user?"} %>
<%= link_to "Permissions", admin_user_permissions_path(@user) %>